// <auto-generated />
using System;
using CliveBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CliveBot.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230210113222_BotModAndCharacterInfo")]
    partial class BotModAndCharacterInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CliveBot.Database.Models.BotModerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermissionsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionsId")
                        .IsUnique();

                    b.ToTable("BotModerators");
                });

            modelBuilder.Entity("CliveBot.Database.Models.BotModeratorPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllPermissions")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManageCharacterInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManageCharacterNotes")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManageCharacters")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManageModerators")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManageSkillInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManageSkillTranslations")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManageSkills")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BotModeratorPermissions");
                });

            modelBuilder.Entity("CliveBot.Database.Models.SkillLanguageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillLanguages");
                });

            modelBuilder.Entity("CliveBot.Database.Models.SkillModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<int?>("MasteredVersionForeignKey")
                        .HasColumnType("integer");

                    b.Property<int>("MasterizationPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("RatingMagical")
                        .HasColumnType("integer");

                    b.Property<int>("RatingPhysical")
                        .HasColumnType("integer");

                    b.Property<int>("Summon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasteredVersionForeignKey")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("CliveBot.Database.Models.BotModerator", b =>
                {
                    b.HasOne("CliveBot.Database.Models.BotModeratorPermissions", "Permissions")
                        .WithOne("Moderator")
                        .HasForeignKey("CliveBot.Database.Models.BotModerator", "PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CliveBot.Database.Models.SkillLanguageModel", b =>
                {
                    b.HasOne("CliveBot.Database.Models.SkillModel", "Skill")
                        .WithMany("Localized")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CliveBot.Database.Models.SkillModel", b =>
                {
                    b.HasOne("CliveBot.Database.Models.SkillModel", "MasteredVersion")
                        .WithOne("PreviousVersion")
                        .HasForeignKey("CliveBot.Database.Models.SkillModel", "MasteredVersionForeignKey");

                    b.Navigation("MasteredVersion");
                });

            modelBuilder.Entity("CliveBot.Database.Models.BotModeratorPermissions", b =>
                {
                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("CliveBot.Database.Models.SkillModel", b =>
                {
                    b.Navigation("Localized");

                    b.Navigation("PreviousVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
